PRAGMA foreign_keys = ON;
CREATE TABLE settings (id INTEGER PRIMARY KEY CHECK(id=1), value TEXT NOT NULL CHECK(json_valid(value)), version INTEGER NOT NULL DEFAULT 1);
INSERT INTO settings(id,value) VALUES(1,'{"orderingEnabled":false,"offersEnabled":false,"taxMode":"unconfirmed","termsVersion":"2026-10-04","shippingMethods":[],"paymentMethods":[],"bankAccount":"","legalReady":false}');
CREATE TABLE admins (id TEXT PRIMARY KEY, label TEXT NOT NULL, key_hash TEXT NOT NULL UNIQUE, enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN(0,1)), created_at TEXT NOT NULL);
CREATE TABLE sessions (hash TEXT PRIMARY KEY, admin_id TEXT NOT NULL REFERENCES admins(id), csrf TEXT NOT NULL, expires_at INTEGER NOT NULL);
CREATE INDEX sessions_expiry ON sessions(expires_at);
CREATE TABLE rate_limits (key TEXT PRIMARY KEY, count INTEGER NOT NULL, expires_at INTEGER NOT NULL);
CREATE TABLE customers (id TEXT PRIMARY KEY, email TEXT NOT NULL UNIQUE, name TEXT NOT NULL, phone TEXT NOT NULL DEFAULT '', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE enquiries (id TEXT PRIMARY KEY, reference TEXT NOT NULL UNIQUE, customer_id TEXT NOT NULL REFERENCES customers(id), kind TEXT NOT NULL, source TEXT NOT NULL, vehicle TEXT NOT NULL DEFAULT '', product_reference TEXT NOT NULL DEFAULT '', message TEXT NOT NULL DEFAULT '', configuration TEXT NOT NULL DEFAULT '{}', status TEXT NOT NULL DEFAULT 'new', created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE INDEX enquiries_created ON enquiries(created_at DESC);
CREATE TABLE products (id TEXT PRIMARY KEY, sku TEXT NOT NULL UNIQUE, title TEXT NOT NULL, description TEXT NOT NULL DEFAULT '', specs TEXT NOT NULL DEFAULT '[]' CHECK(json_valid(specs)), image TEXT NOT NULL DEFAULT '', price_cents INTEGER CHECK(price_cents IS NULL OR price_cents>0), currency TEXT NOT NULL DEFAULT 'CZK' CHECK(currency='CZK'), wheels_per_set INTEGER NOT NULL DEFAULT 4 CHECK(wheels_per_set BETWEEN 1 AND 8), on_hand INTEGER NOT NULL DEFAULT 0 CHECK(on_hand>=0), reserved INTEGER NOT NULL DEFAULT 0 CHECK(reserved>=0 AND reserved<=on_hand), published INTEGER NOT NULL DEFAULT 0 CHECK(published IN(0,1)), confirmed INTEGER NOT NULL DEFAULT 0 CHECK(confirmed IN(0,1)), version INTEGER NOT NULL DEFAULT 1, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, CHECK(published=0 OR (confirmed=1 AND price_cents IS NOT NULL)));
CREATE TABLE orders (id TEXT PRIMARY KEY, reference TEXT NOT NULL UNIQUE, customer_id TEXT NOT NULL REFERENCES customers(id), kind TEXT NOT NULL CHECK(kind IN('stock','custom')), idempotency_key TEXT NOT NULL UNIQUE, request_hash TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN('pending','paid','fulfilled','cancelled','closed')), customer_snapshot TEXT NOT NULL CHECK(json_valid(customer_snapshot)), shipping_snapshot TEXT NOT NULL CHECK(json_valid(shipping_snapshot)), payment_snapshot TEXT NOT NULL CHECK(json_valid(payment_snapshot)), specification TEXT NOT NULL DEFAULT '{}', subtotal_cents INTEGER NOT NULL CHECK(subtotal_cents>=0), shipping_cents INTEGER NOT NULL CHECK(shipping_cents>=0), total_cents INTEGER NOT NULL CHECK(total_cents=subtotal_cents+shipping_cents), currency TEXT NOT NULL DEFAULT 'CZK' CHECK(currency='CZK'), terms_version TEXT NOT NULL, tax_mode TEXT NOT NULL, accepted_at TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, version INTEGER NOT NULL DEFAULT 1);
CREATE INDEX orders_created ON orders(created_at DESC);
CREATE TABLE order_items (id TEXT PRIMARY KEY, order_id TEXT NOT NULL REFERENCES orders(id), product_id TEXT NOT NULL REFERENCES products(id), quantity INTEGER NOT NULL CHECK(quantity BETWEEN 1 AND 100), unit_price_cents INTEGER NOT NULL CHECK(unit_price_cents>0), snapshot TEXT NOT NULL CHECK(json_valid(snapshot)), UNIQUE(order_id,product_id));
CREATE TABLE stock_movements (id TEXT PRIMARY KEY, product_id TEXT NOT NULL REFERENCES products(id), order_id TEXT REFERENCES orders(id), kind TEXT NOT NULL, delta_on_hand INTEGER NOT NULL DEFAULT 0, delta_reserved INTEGER NOT NULL DEFAULT 0, reason TEXT NOT NULL, actor TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE audit (id TEXT PRIMARY KEY, actor TEXT NOT NULL, action TEXT NOT NULL, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, details TEXT NOT NULL DEFAULT '{}', created_at TEXT NOT NULL);
CREATE TABLE notes (id TEXT PRIMARY KEY, entity_type TEXT NOT NULL CHECK(entity_type IN('enquiry','order','customer')), entity_id TEXT NOT NULL, body TEXT NOT NULL, actor TEXT NOT NULL, created_at TEXT NOT NULL);
CREATE TABLE outbox (id TEXT PRIMARY KEY, entity_type TEXT NOT NULL, entity_id TEXT NOT NULL, recipient TEXT NOT NULL, template TEXT NOT NULL, payload TEXT NOT NULL CHECK(json_valid(payload)), status TEXT NOT NULL DEFAULT 'blocked' CHECK(status IN('blocked','pending','sending','sent','failed')), attempts INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL, sent_at TEXT, last_error TEXT NOT NULL DEFAULT 'Email provider is not configured');
CREATE INDEX outbox_status ON outbox(status,created_at);
CREATE TABLE offers (id TEXT PRIMARY KEY, enquiry_id TEXT NOT NULL REFERENCES enquiries(id), token_hash TEXT NOT NULL UNIQUE, snapshot TEXT NOT NULL CHECK(json_valid(snapshot)), expires_at INTEGER NOT NULL, status TEXT NOT NULL DEFAULT 'open' CHECK(status IN('open','accepted','revoked')), order_id TEXT REFERENCES orders(id), created_at TEXT NOT NULL);
CREATE TABLE assertions (ok INTEGER NOT NULL CHECK(ok=1));
CREATE TRIGGER reserve_stock BEFORE INSERT ON order_items BEGIN
  SELECT RAISE(ABORT,'STOCK_OR_PRICE_CHANGED') WHERE NOT EXISTS(SELECT 1 FROM products WHERE id=NEW.product_id AND published=1 AND confirmed=1 AND price_cents=NEW.unit_price_cents AND on_hand-reserved>=NEW.quantity);
  UPDATE products SET reserved=reserved+NEW.quantity,version=version+1 WHERE id=NEW.product_id;
  INSERT INTO stock_movements(id,product_id,order_id,kind,delta_reserved,reason,actor,created_at) VALUES(lower(hex(randomblob(16))),NEW.product_id,NEW.order_id,'reserve',NEW.quantity,'Online order','checkout',strftime('%Y-%m-%dT%H:%M:%fZ','now'));
END;
CREATE TRIGGER protect_order_items BEFORE UPDATE ON order_items BEGIN SELECT RAISE(ABORT,'IMMUTABLE_ORDER_ITEM'); END;
CREATE TRIGGER protect_order_items_delete BEFORE DELETE ON order_items BEGIN SELECT RAISE(ABORT,'IMMUTABLE_ORDER_ITEM'); END;
CREATE TRIGGER protect_order_snapshot BEFORE UPDATE OF customer_snapshot,shipping_snapshot,payment_snapshot,specification,subtotal_cents,shipping_cents,total_cents,currency,terms_version,tax_mode,accepted_at,request_hash,idempotency_key,customer_id,kind ON orders BEGIN SELECT RAISE(ABORT,'IMMUTABLE_ORDER'); END;
CREATE TRIGGER order_transition BEFORE UPDATE OF status ON orders WHEN OLD.status<>NEW.status BEGIN
 SELECT RAISE(ABORT,'INVALID_ORDER_TRANSITION') WHERE NOT ((OLD.status='pending' AND NEW.status IN('paid','cancelled')) OR (OLD.status='paid' AND NEW.status IN('fulfilled','cancelled')) OR (OLD.status='fulfilled' AND NEW.status='closed'));
END;
CREATE TRIGGER order_cancel AFTER UPDATE OF status ON orders WHEN NEW.status='cancelled' AND OLD.status IN('pending','paid') BEGIN
 INSERT INTO stock_movements(id,product_id,order_id,kind,delta_reserved,reason,actor,created_at) SELECT lower(hex(randomblob(16))),product_id,NEW.id,'release',-quantity,'Order cancelled','admin',NEW.updated_at FROM order_items WHERE order_id=NEW.id;
 UPDATE products SET reserved=reserved-(SELECT quantity FROM order_items WHERE order_id=NEW.id AND product_id=products.id),version=version+1 WHERE id IN(SELECT product_id FROM order_items WHERE order_id=NEW.id);
END;
CREATE TRIGGER order_fulfill AFTER UPDATE OF status ON orders WHEN NEW.status='fulfilled' AND OLD.status='paid' BEGIN
 INSERT INTO stock_movements(id,product_id,order_id,kind,delta_on_hand,delta_reserved,reason,actor,created_at) SELECT lower(hex(randomblob(16))),product_id,NEW.id,'ship',-quantity,-quantity,'Order fulfilled','admin',NEW.updated_at FROM order_items WHERE order_id=NEW.id;
 UPDATE products SET reserved=reserved-(SELECT quantity FROM order_items WHERE order_id=NEW.id AND product_id=products.id),on_hand=on_hand-(SELECT quantity FROM order_items WHERE order_id=NEW.id AND product_id=products.id),version=version+1 WHERE id IN(SELECT product_id FROM order_items WHERE order_id=NEW.id);
END;
