'use strict';
// Run with the static site served on NFW_BASE_URL (default :8765).
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const base = process.env.NFW_BASE_URL || 'http://127.0.0.1:8765';
const shots = path.join(__dirname, '../docs/qa');

(async () => {
  fs.mkdirSync(shots, { recursive: true });
  const browser = await chromium.launch({ channel: 'chrome', headless: true,
    args: ['--use-gl=angle', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
  const page = await context.newPage();
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const open = url => page.goto(base + url, { waitUntil: 'networkidle' });
  const ready3D = async () => { await page.locator('.webgl-view canvas').waitFor(); await page.waitForFunction(() => !document.querySelector('.viewer-loading')); };
  const hash = () => page.evaluate(() => Object.fromEntries(new URLSearchParams(location.hash.slice(1))));
  const noOverflow = async () => assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'No horizontal overflow');

  await open('/');
  assert.match(await page.title(), /Need For Wheels/);
  assert.equal(await page.locator('svg').count(), 0);
  await page.screenshot({ path: path.join(shots, 'home-desktop.png') });
  // Force lazy media to load, rather than treating unrequested offscreen images as broken.
  await page.locator('img').evaluateAll(images => images.forEach(image => image.loading = 'eager'));
  await page.waitForFunction(() => [...document.images].every(i => i.complete && i.naturalWidth > 0));
  assert.equal(await page.locator('#designsGrid a').count(), 13);
  await page.locator('#designy .section__head').scrollIntoViewIfNeeded();
  await page.screenshot({ path: path.join(shots, 'collection-desktop.png') });
  await page.locator('[data-launch-wheel]').click();
  await page.locator('#featureWheel canvas').waitFor();
  assert.equal(await page.locator('#featureWheel > img').count(), 0, '3D replaces original product photo');
  console.log('PASS home, all image assets, 13 product renders and inline 3D launch');

  await open('/konfigurator.html'); await ready3D();
  assert.equal(await page.locator('#vehicleBrand option').count(), 53);
  assert.equal(await page.locator('#vehicleBrand').inputValue(), 'bmw');
  await noOverflow(); await page.screenshot({ path: path.join(shots, 'config-desktop.png') });
  await page.getByRole('button', { name: 'Můj vůz', exact: true }).click();
  await page.selectOption('#vehicleYear', '2008');
  assert.match(await page.locator('.vehicle-render').getAttribute('src'), /e70/);
  await page.selectOption('#vehicleYear', '2020');
  assert.match(await page.locator('.vehicle-render').getAttribute('src'), /g05/);
  await page.screenshot({ path: path.join(shots, 'config-car.png') });
  await page.selectOption('#vehicleYear', '2023');
  assert.equal(await page.locator('#vehicleGeneration').inputValue(), '');
  assert.equal(await page.locator('.vehicle-render').count(), 0, 'Transition year must not select a body');
  await page.selectOption('#vehicleGeneration', 'g05');
  assert.match(await page.locator('.vehicle-render').getAttribute('src'), /g05/);
  await page.selectOption('#vehicleBrand', 'skoda'); await page.selectOption('#vehicleModel', 'octavia');
  await ready3D();
  assert.match(await page.locator('.preview-caption').innerText(), /zatím nemáme přesný/);
  assert.equal(await page.locator('.vehicle-render').count(), 0);
  console.log('PASS exact generations, transition choice and missing asset fallback');

  await page.locator('[data-set=carDetail]').fill('RS, generace IV');
  await page.getByRole('button', { name: '3D kolo', exact: true }).click(); await ready3D();
  await page.locator('[data-step="2"]').click();
  await page.locator('[data-set=design][data-val=mesh3pc]').click();
  await page.locator('[data-step="3"]').click();
  await page.locator('[data-set=d][data-val="21"]').click();
  await page.locator('#stagToggle').uncheck();
  const width = page.locator('[data-set=wf]');
  await width.fill('9.5'); await width.dispatchEvent('input');
  await page.locator('[data-set=note]').fill('Větší brzdy; ověřit prostor.');
  await page.locator('[data-step="4"]').click();
  assert.match(await page.locator('[data-set=cap][data-val=carbon]').innerText(), /Karbonová/);
  await page.locator('[data-set=color][data-val=blue]').last().click();
  await page.locator('[data-set=finish][data-val=brushed]').click();
  await page.locator('[data-set=cap][data-val=none]').click();
  await page.locator('[data-extra=ceramic]').check();
  await page.locator('[data-step="5"]').click();
  const before = await hash(); const url = page.url();
  assert.equal(before.wf, before.wr);
  assert.equal(before.model, 'octavia');
  await page.locator('[data-set=name]').fill('Test User');
  await page.locator('[data-set=email]').fill('test@example.test');
  assert.doesNotMatch(page.url(), /Test|example/);
  await page.reload({ waitUntil: 'networkidle' }); await ready3D();
  assert.deepEqual(await hash(), before, 'Full configuration roundtrip');
  const summary = await page.locator('.spec').first().innerText();
  for (const text of ['Octavia', 'RS, generace IV', 'MESH 3PC', 'Bez krytky', 'Větší brzdy']) assert.ok(summary.includes(text), text);
  await page.screenshot({ path: path.join(shots, 'summary-desktop.png') });
  await page.locator('#sendMail').evaluate(el => el.addEventListener('click', event => event.preventDefault()));
  await page.locator('#sendMail').click();
  assert.match(decodeURIComponent(await page.locator('#sendMail').getAttribute('href')), /Need For Wheels.*Octavia/s);
  console.log('PASS five steps, color/material/cap/size, summary, email draft and URL roundtrip');

  await open('/konfigurator.html#brand=%C5%A0koda&model=Octavia&year=2020&x=ceramic,ceramic&step=4');
  assert.equal((await hash()).brand, 'skoda');
  assert.equal((await hash()).model, 'octavia');
  assert.equal((await hash()).x, 'ceramic');
  await page.evaluate(() => { location.hash = 'brand=bmw&model=x5&year=2023&view=car'; });
  await page.waitForFunction(() => document.querySelector('#vehicleYear')?.value === '2023');
  assert.equal(await page.locator('#vehicleGeneration').inputValue(), '');
  assert.equal(await page.locator('.vehicle-render').count(), 0);
  await page.evaluate(() => { location.hash = 'brand=%3Cscript%3E&model=%22%3E&d=999&colorHex=not-a-color&wf=-10'; });
  await page.waitForFunction(() => new URLSearchParams(location.hash.slice(1)).get('d') === '24');
  assert.equal((await hash()).wf, '7');
  assert.equal((await hash()).brand, 'bmw');
  assert.equal(await page.locator('svg').count(), 0);
  console.log('PASS URL canonical IDs, duplicate extras, hash navigation and invalid input');

  await page.getByRole('button', { name: '3D showroom', exact: true }).click(); await ready3D();
  assert.match(await page.locator('.preview-caption').innerText(), /Ferrari 458 Italia/);
  await page.screenshot({ path: path.join(shots, 'config-ferrari.png') });
  await page.getByRole('button', { name: '3D kolo', exact: true }).click(); await ready3D();
  assert.equal(await page.locator('canvas').count(), 1);
  console.log('PASS real car load and wheel/car context replacement');

  await page.setViewportSize({ width: 390, height: 844 });
  await open('/'); await noOverflow(); await page.screenshot({ path: path.join(shots, 'home-mobile.png') });
  await page.locator('.burger').click(); assert.equal(await page.locator('.burger').getAttribute('aria-expanded'), 'true');
  await page.keyboard.press('Escape'); assert.equal(await page.locator('.burger').getAttribute('aria-expanded'), 'false');
  await open('/konfigurator.html'); await ready3D(); await noOverflow();
  await page.screenshot({ path: path.join(shots, 'config-mobile.png') });
  await page.locator('.nfw-brand-field .nfw-brand-trigger').scrollIntoViewIfNeeded();
  assert.ok(await page.locator('.nfw-brand-field .nfw-brand-trigger').isVisible());
  await page.selectOption('#vehicleBrand', 'tesla'); await page.selectOption('#vehicleModel', 'model-y');
  assert.equal((await hash()).model, 'model-y');
  await noOverflow(); await page.screenshot({ path: path.join(shots, 'config-mobile-form.png') });
  await open('/proces.html');
  assert.equal(await page.locator('video').count(), 2);
  assert.equal(await page.locator('text=Místo pro').count(), 0);
  await noOverflow();
  console.log('PASS mobile navigation, vehicle controls, layout and reference videos');
  assert.deepEqual(errors, [], 'No page runtime errors');
  await browser.close(); console.log('UI integration checks passed.');
})().catch(error => { console.error(error); process.exit(1); });
